# Use the official Node.js 14 image as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .

# Expose port 3000
EXPOSE 3000

# Setup the database and grant privileges
RUN apt-get update && \
    apt-get install -y postgresql-client && \
    export PGPASSWORD=mysecretpassword && \
    psql -h postgresql.test-project.svc.cluster.local -U developer -d todo_list -c 'CREATE DATABASE todo_list;' && \
    psql -h postgresql.test-project.svc.cluster.local -U developer -d todo_list -c 'GRANT ALL PRIVILEGES ON DATABASE todo_list TO developer;'

# Command to run the application
CMD ["node", "index.js"]
